var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                             o  ",
   "                                                                           xxxx ",
   "                                              xxxxx                             ",
   "                                                                  xxx           ",
   "                                                           xx  xxxx!xx          ",
   "                                                               x!!!!!xxx        ",
   "                                  xxxxxxx                      vxx!!xxv         ",
   "                                                                  v x         xx",
   "                                                 xxx                            ",
   "  xx                                                                            ",
   "  x                                                                        xx   ",
   "  x                                      xxxxx                                  ",
   "  x                                                                             ",
   "  x  @       xxxx    o     o                                       xxx          ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     x         x          ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     x         x          ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxx!!!!!!xxxxxxx     x   xxxxx x          ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxx!!!!!!xxxxx     x  xx!!!xxx          ",
   "  xxxxxxxxxxxxxxxxxx!!!!!!xxxxx   xxxxx!!!!!!xxxxxxxxx!!!!!xxxx!!x!!xx!!!!!!!!!!",
   "  xxxxxxxxxxxxxxxx!!!!!!!!!!xxx   xxxxxxxxx!!!!!!xxxxx!!!!!xx!!!xxx!!x!!!!!!!!!!",
   "  xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                       xxxxx!!x       x!!xxxxxx                   xxxxxxxxxxxxxxxxx                          !!!!!",
   "                    =  xxxxx!!x   @   x!!xxxxxxx               xxxxxxxxxxxxxxxxxxxxxxx                    v  !!!!!",
   "                    xxxxxxxx!!x       x!!xxxxxxxxxx           xxxxxxxv  v  v  v  xxxxxx                   v v!!!!!",
   "     o             xx!!!!!!!!xx       xx!!!!!!!!!!xx      xxxxxxxv               v xxxxxxxxxxxxxxvxxxxxxxx  v!!!!!",
   "     x             x!!xxxxxxxx         xxxxxxxxxx!!xxxxxxxxxxx                     vxxxxvxxxvxxxx xxxxxxxxv  !!!!!",
   "                   x!xx                         xx!xxxxxxxxxv                                             v v!!!!!",
   "               xx  x!x                           x!xxxxxxxxx v               x                              v!!!!!",
   "                    v                            xvxxxxxxx                                                v  !!!!!",
   "                                                  |                                                       v  !!!!!",
   "    xxx                                           v                                 x                        !!!!!",
   "                                                                      xxx                                    !!!!!",
   "                                                  v                                           =    x         !!!!!",
   "             xxxx           xxxxxxxxxxxxx         |                        x                      xxx        !!!!!",
   "                                                  v x        xxx                                             !!!!!",
   "                                         =       xxxxx                                                    x  !!!!!",
   "                                               xxxxxx                  x                                  x  !!!!!",
   "    xx      xxxxxx      xx                    xxxxxxxxxxx              v                                  x  !!!!!",
   "!!!!!x!!!!!!x!!!!x!!!!!!x                     x                                         x                 x  !!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxx                     x                        v                                  x  !!!!!",
   "x                                           xxx                        |                          x       x!!!!!!!",
   "x                                           x            xxxxxxxx      v                                  xxvxxxxx",
   "x                                           x                                 x                              xxxxx",
   "x    xxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxx                          v                                      xxxx",
   "x            xxx                                     x!!!!!!!!!!       x                                       xxx",
   "x            xx                                      x!!!!!!!xx!       x                                          ",
   "x            x                                      xx!!!!!!xx !       x                    x                  o  ",
   "x                                                  xx!!!!!!xx  !       x =        =       =                 xxxxxx",
   "x                                                 xxx!!!!!xx   !       xxxxxxxxxxxxxxxxxxxxxx        xx           ",
   "x      o               xxx!!!!!!!!!xxxx!!!!!!xxxxxxx!!!!!xx    !                                                  ",
   "xxxxxxxxxxxxxxx        x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                              xxxx                            ",
   "                                                                             xx!!xx                           ",
   "                                                                            xxxxxxxx                          ",
   "                                                                            !      !                  xxxx    ",
   "                                                                            v                        xx!!xx   ",
   "                                        !                                          v                xxxxxxxx  ",
   "                                        !                                                              !!     ",
   "                                        x                                                              v      ",
   "                                     !  x  !                                                                  ",
   "                                     ! xxx !                                                            v     ",
   "                                     xxx!xxx                                                                  ",
   "                                      x!!!x                                                                   ",
   "                                      x!!!x                                            xxx                    ",
   "                                      x!!!x                  !!!!!!xxxxx                 xx                   ",
   "                                     xx!!!xx!!!!!!x   x!!!!!!xxxxxxxx                                         ",
   "                                      x!!!xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x!!!x           x                    x!!!x                xxx           ",
   "                                      x!!!x           x                    vxxxv                              ",
   "                                     xx!!!xx          x                                                       ",
   "                                      x!!!x     o     x                                                     xx",
   "                                      x!!!x o o   o o x                                                       ",
   "                                      x!!!x     o     x           xxxx                             xxx        ",
   "                                     xx!!!xxxxxxxxxxxxx                                         xxxx v        ",
   "                                      x!!!x           x                                        x!!!x          ",
   "                                      x!!!x           x                                        xxxx           ",
   "                                     xxx!xx                                                   xx              ",
   "                               xxxxxxxxxxxx                                                                   ",
   "                                 xxxxxxxxxx    xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                                  xxxxxxxxx                                          xxx                      ",
   "  xxx                               xxxxxxx                                         x!!!x                xxxxx",
   "  x x                                 xxxxxx                                         xxx         x       x!!!x",
   "  x                                   xxxxxxxxxx  |         |                                             !!! ",
   "  x                                    xxxx                                                               !!! ",
   "  x                         xxxxxxxxxxxxxxx            |                                                  !!! ",
   "  x                       xxxxxxxxxxxxxxxxx!!!!!!! xxxx !!!! xxxx|                                        !!! ",
   "  x                xxxxxxxxxxxxx        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxx                   !!! ",
   "  x                                                                                            xxxxx      !!! ",
   "  x                     |                    |     |           |                            xxxx          !!! ",
   "  x                           |         o             |     |                           xxxxxxx          !!!! ",
   "  x      @                                                                         xxxxxxxxxxxx         !!!x! ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!x! ",
   "                                                                                                        !!! ! ",
   "                                                                                                        !!! ! "],
  ["                                                                                                              ",
   "                          v            v             v               v                v                       ",
   "                                v           v                v              v                 v               ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                               o                                                                              ",
   "                      x        x                                       o                                      ",
   "                      x    |                                           x                                      ",
   "                      xx       x                                                                              ",
   "                               x                                               x                              ",
   "                              xx                                                                            xx",
   "                     x                     o                                        x                        v",
   "                     x                     x                                                                  ",
   "                     xxx                            x                                                         ",
   "                                                                                          x                   ",
   "      x=                      xx                                                                              ",
   "                                      xx       xx                                                             ",
   "                    x=                                          x                                  x        xx",
   "                                                                                                              ",
   "                          =                                                                                   ",
   "                                xxx                xxxxxxxx           x                       x               ",
   "                                                                         x         x                        xx",
   "                                                                                                              ",
   "   xxxxxxxxxxxx                          xxxx                                           x                     ",
   "              x                                                              x                                ",
   "              x                                                                                             xx",
   "     @        xxxxxxxx             xxx          xxx                                                           ",
   "  xxxxxxx                                                                                                     ",
   "  xxxxxxx            =                    = x                                                      xx         ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                      xx         ",
   "                                                                                                              ",
   "                                             !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
